/*==============================================================*/
/*  File Name   : SentenceBuilderDatabase.sql                   */
/*  Description : Creates the tables of the database and links  */
/*                them all together                             */
/*                                                              */
/*  Author      : Cortland Kimzey                               */
/*  Created On  : 2026-01-29                                    */
/*                                                              */
/*  Last Modified By : Cortland Kimzey                          */
/*  Last Modified On : 2026-03-09                               */
/*  Change History : 2026-02-02 - Add header and table          */
/*                                descriptions                  */
/*                : 2026-03-09 - Fix syntax for MySQL,          */
/*                                add missing columns,          */
/*                                add generatedSentence table   */
/*                                                              */
/*  Database    : SentenceBuilder                               */
/*==============================================================*/

CREATE DATABASE IF NOT EXISTS SentenceBuilder;
USE SentenceBuilder;

-- One table for each txt file to hold different info about them
CREATE TABLE txt (
    txtID        INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    txtName      VARCHAR(64) NOT NULL,
    importance   INT,
    numWords     INT,
    numSentences INT,
    importedAt   DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- One table for every unique word found in the txt files
-- count     = total number of times this word appears
-- startCount = number of times this word starts a sentence
-- endCount   = number of times this word ends a sentence
CREATE TABLE word (
    wordID     INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    word       VARCHAR(64) NOT NULL,
    count      INT NOT NULL DEFAULT 0,
    startCount INT NOT NULL DEFAULT 0,
    endCount   INT NOT NULL DEFAULT 0,
    UNIQUE (word)
);

-- One table for each sentence in a txt file
-- Tracks the first and last word of each sentence
-- and stores the full sentence text for duplicate detection
CREATE TABLE sentence (
    sentenceID  INT NOT NULL AUTO_INCREMENT,
    txtID       INT NOT NULL,
    firstWordID INT NOT NULL,
    lastWordID  INT NOT NULL,
    full_text   TEXT,
    PRIMARY KEY (sentenceID, txtID),
    FOREIGN KEY (txtID)       REFERENCES txt(txtID),
    FOREIGN KEY (firstWordID) REFERENCES word(wordID),
    FOREIGN KEY (lastWordID)  REFERENCES word(wordID)
);

-- One table for every combination of two words to track
-- how often a word appears after another word
CREATE TABLE nextWord (
    wordID     INT NOT NULL,
    nextWordID INT NOT NULL,
    count      INT NOT NULL DEFAULT 1,
    PRIMARY KEY (wordID, nextWordID),
    FOREIGN KEY (wordID)     REFERENCES word(wordID),
    FOREIGN KEY (nextWordID) REFERENCES word(wordID)
);

-- Tracks all sentences that have been generated by the program
-- algorithm = which generation method was used (e.g. 'random', 'weighted')
-- Used for the duplicate detection report
CREATE TABLE generatedSentence (
    genID       INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    full_text   TEXT,
    algorithm   VARCHAR(32),
    generatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
